

prompts:
  system_prompt_question: |
    You are an expert financial analyst skilled in generating questions that are meaningful for financial analysis or generating insights from scraped financial webpages/pdfs. 
    Your task involves analyzing text of a scraped financial webpage/pdf to generate relevant questions. 
    While performing this task, you must adhere to a set of specified constraints.
  #SINGLE TABLE SINGLE QUESTION
  q_generation_1T1Q: |
    Given an extract from a financial webpage/pdf, generate a financial reasoning question. Please adhere to the following constraints meticulously when formulating the question.
    Constraints:
    1. The question must be generated such that it always leads to a single numerical or boolean answer.
    2. The question must be strictly derived from the content present in the extract.
    3. Answering the question should require the use of values from the table and/or values present in the text around the table.
    4. Calculating the answer should involve multi-hop reasoning with the following arithmetic operations:
      -Basic operations: Addition, Subtraction, Multiplication, Division, Exponential, Greater Than
      -Table aggregation operations: Sum, Average, Minimum, Maximum

    The final response should be formatted as a JSON format with only the question and no other objects should be included:
    [
      {{
        "Question": "Question 1?"
      }}
    ]

    Extract:
    {text}
  # SINGLE TABLE 5 QUESTIONS
  q_generation_1T5Q: |
    Given an extract from a financial webpage/pdf, generate 5 financial reasoning questions. Please adhere to the following constraints meticulously when formulating the questions.
    Constraints:
    1. The questions must be generated such that they always lead to a single numerical or boolean answer.
    2. Each question should use concepts different than the concepts used in any of the other questions.
    3. The questions must be strictly derived from the content present in the extract.
    4. Answering the questions should require the use of values from the table and/or values present in the text around the table.
    5. Calculating the answer should involve multi-hop reasoning with the following arithmetic operations:
      -Basic operations: Addition, Subtraction, Multiplication, Division, Exponential, Greater Than
      -Table aggregation operations: Sum, Average, Minimum, Maximum

    The final response should be formatted as a JSON format with only the questions and no other objects should be included:
    [
      {{
        "Question": "Question 1?"
      }},
      {{
        "Question": "Question 2?"
      }}
    ]

    Extract:
    {text}
  
  #MULTIPLE TABLES ONE QUESTION:
  q_generation_5T1Q: |
    Given an extract from a financial webpage/pdf, generate a financial reasoning question. Please adhere to the following constraints meticulously when formulating the question.
    Constraints:
    1. The question must be generated such that it always leads to a single numerical or boolean answer.
    2. The question must be strictly derived from the content present in the extract.
    3. Answering the question should require the use of values from at least two distinct tables in the extract; the question may also rely on values that appear in the text surrounding those tables. 
    4. Calculating the answer should involve multi-hop reasoning with the following arithmetic operations:
      -Basic operations: Addition, Subtraction, Multiplication, Division, Exponential, Greater Than
      -Table aggregation operations: Sum, Average, Minimum, Maximum

    The final response should be formatted as a JSON format with only the question and no other objects should be included:
    [
      {{
        "Question": "Question 1?"
      }}
    ]

    Extract:
    {text}

  #MULTIPLE TABLES 5 QUESTIONS:
  q_generation_5T5Q: |
    Given an extract from a financial webpage/pdf, generate 5 financial reasoning questions. Please adhere to the following constraints meticulously when formulating the questions.
    Constraints:
    1. The questions must be generated such that they always lead to a single numerical or boolean answer.
    2. Each question should use concepts different than the concepts used in any of the other questions.
    3. The questions must be strictly derived from the content present in the extract.
    4. Answering the questions should require the use of values from at least two distinct tables in the extract; the questions may also rely on values that appear in the text surrounding those tables. 
    5. Calculating the answer should involve multi-hop reasoning with the following arithmetic operations:
      -Basic operations: Addition, Subtraction, Multiplication, Division, Exponential, Greater Than
      -Table aggregation operations: Sum, Average, Minimum, Maximum

    The final response should be formatted as a JSON format with only the questions and no other objects should be included:
    [
      {{
        "Question": "Question 1?"
      }},
      {{
        "Question": "Question 2?"
      }}
    ]

    Extract:
    {text}


  system_prompt_reasoning: |
    You are an expert financial analyst skilled in answering financial reasoning questions.

  reasoning_generation: |
    Given a question and the corresponding context, generate a step-by-step reasoning trace. The reasoning trace must lead to the answer which is to be given separately. The answer is always boolean or numeric.
    The reasoning trace must be clear, logically sound, grounded in the context and result in a definitive answer.

    ### Context:
    {text}

    ### Question:
    {question}

    ### Reasoning:  
